In [203]:
import requests
import matplotlib.pyplot as plt
import json
import pandas as pd
import seaborn as sns

In [204]:
endpoint = 'https://api.worldbank.org/v2/country/all/indicator/NY.GDP.PCAP.PP.KD?'
parameters = {
    'format': 'json',
    'per_page': '17490'
}
request = requests.get(endpoint, params = parameters)

In [205]:
request

In [206]:
res = request.json()

In [207]:
res

[{'page': 1,
  'pages': 1,
  'per_page': 17490,
  'total': 17490,
  'sourceid': '2',
  'lastupdated': '2026-07-01'},
 [{'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2025',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2024',
   'value': 4106.43414035047,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2023',
   'value': 4083.99300263507,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2022',
   'value': 4106.50190693219,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2021',
   'value': 4056.11301700129,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2020',
   'value': 3978.93139450095,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2019',
   'value': 4195.86541780344,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2018',
   'value': 4220.91250168849,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2017',
   'value': 4214.39708524398,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2016',
   'value': 4202.23641584707,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2015',
   'value': 4206.25295270438,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2014',
   'value': 4185.23841104229,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2013',
   'value': 4125.18256263035,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2012',
   'value': 4061.64163525859,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2011',
   'value': 4042.84247175787,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2010',
   'value': 3976.01098918458,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2009',
   'value': 3869.99812557719,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2008',
   'value': 3934.08423728651,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2007',
   'value': 3866.72395287147,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2006',
   'value': 3718.02241324132,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2005',
   'value': 3577.58589657798,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2004',
   'value': 3457.12022216505,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2003',
   'value': 3357.24486194198,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2002',
   'value': 3350.14106469179,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2001',
   'value': 3313.42192907347,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2000',
   'value': 3281.92231355821,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1999',
   'value': 3267.96274823069,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1998',
   'value': 3269.06995117859,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1997',
   'value': 3291.25656501965,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1996',
   'value': 3246.82586499728,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1995',
   'value': 3154.79090002396,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1994',
   'value': 3099.31243976356,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1993',
   'value': 3127.2935723296,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1992',
   'value': 3251.64780568922,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1991',
   'value': 3424.50025403354,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1990',
   'value': 3519.3175448125,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1989',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1988',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1987',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1986',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1985',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1984',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1983',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1982',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1981',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1980',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1979',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1978',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1977',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1976',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1975',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1974',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1973',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1972',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1971',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1970',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1969',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1968',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1967',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1966',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1965',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1964',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1963',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1962',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},

In [208]:
res[0]

{'page': 1,
 'pages': 1,
 'per_page': 17490,
 'total': 17490,
 'sourceid': '2',
 'lastupdated': '2026-07-01'}

In [209]:
thing = pd.DataFrame(res[1])

In [210]:
thing

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2025,NaN,,,0
1,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2024,4106.434140,,,0
2,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2023,4083.993003,,,0
3,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2022,4106.501907,,,0
4,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2021,4056.113017,,,0
...,...,...,...,...,...,...,...,...
17485,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'ZW', 'value': 'Zimbabwe'}",ZWE,1964,NaN,,,0
17486,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'ZW', 'value': 'Zimbabwe'}",ZWE,1963,NaN,,,0
17487,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'ZW', 'value': 'Zimbabwe'}",ZWE,1962,NaN,,,0
17488,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'ZW', 'value': 'Zimbabwe'}",ZWE,1961,NaN,,,0
17489,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'ZW', 'value': 'Zimbabwe'}",ZWE,1960,NaN,,,0

In [211]:
thing.dtypes

indicator           object
country             object
countryiso3code     object
date                object
value              float64
unit                object
obs_status          object
decimal              int64
dtype: object

In [212]:
thing['indicator'][0]['value']

'GDP per capita, PPP (constant 2021 international $)'

In [213]:
thing['indicator'] = thing['indicator'].apply(lambda x : x['value'])

In [214]:
thing['indicator']

0        GDP per capita, PPP (constant 2021 internation...
1        GDP per capita, PPP (constant 2021 internation...
2        GDP per capita, PPP (constant 2021 internation...
3        GDP per capita, PPP (constant 2021 internation...
4        GDP per capita, PPP (constant 2021 internation...
                               ...
17485    GDP per capita, PPP (constant 2021 internation...
17486    GDP per capita, PPP (constant 2021 internation...
17487    GDP per capita, PPP (constant 2021 internation...
17488    GDP per capita, PPP (constant 2021 internation...
17489    GDP per capita, PPP (constant 2021 internation...
Name: indicator, Length: 17490, dtype: object

In [215]:
thing['indicator'] = thing['indicator'].str.split('(', expand = True)[0]

In [216]:
thing['country'] = thing['country'].apply(lambda x : x['value'])

In [217]:
gdp = thing.copy()

In [218]:
gdp

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,"GDP per capita, PPP",Africa Eastern and Southern,AFE,2025,NaN,,,0
1,"GDP per capita, PPP",Africa Eastern and Southern,AFE,2024,4106.434140,,,0
2,"GDP per capita, PPP",Africa Eastern and Southern,AFE,2023,4083.993003,,,0
3,"GDP per capita, PPP",Africa Eastern and Southern,AFE,2022,4106.501907,,,0
4,"GDP per capita, PPP",Africa Eastern and Southern,AFE,2021,4056.113017,,,0
...,...,...,...,...,...,...,...,...
17485,"GDP per capita, PPP",Zimbabwe,ZWE,1964,NaN,,,0
17486,"GDP per capita, PPP",Zimbabwe,ZWE,1963,NaN,,,0
17487,"GDP per capita, PPP",Zimbabwe,ZWE,1962,NaN,,,0
17488,"GDP per capita, PPP",Zimbabwe,ZWE,1961,NaN,,,0
17489,"GDP per capita, PPP",Zimbabwe,ZWE,1960,NaN,,,0

In [219]:
endpoint = 'https://api.worldbank.org/v2/country/all/indicator/SP.DYN.LE00.IN?'
parameters = {
    'format': 'json',
    'per_page': '17490'
}
request = requests.get(endpoint, params = parameters)

In [220]:
request

In [221]:
life = request.json()

In [222]:
life[0]

{'page': 1,
 'pages': 1,
 'per_page': 17490,
 'total': 17490,
 'sourceid': '2',
 'lastupdated': '2026-07-01'}

In [223]:
life = pd.DataFrame(life[1])

In [224]:
life

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2025,NaN,,,0
1,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2024,65.349930,,,0
2,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2023,65.146228,,,0
3,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2022,64.487152,,,0
4,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2021,62.979999,,,0
...,...,...,...,...,...,...,...,...
17485,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'ZW', 'value': 'Zimbabwe'}",ZWE,1964,55.431000,,,0
17486,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'ZW', 'value': 'Zimbabwe'}",ZWE,1963,54.942000,,,0
17487,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'ZW', 'value': 'Zimbabwe'}",ZWE,1962,54.453000,,,0
17488,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'ZW', 'value': 'Zimbabwe'}",ZWE,1961,53.966000,,,0
17489,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'ZW', 'value': 'Zimbabwe'}",ZWE,1960,53.492000,,,0

In [225]:
life['indicator'] = life['indicator'].apply(lambda x : x['value'])

In [226]:
life['country'] = life['country'].apply(lambda x : x['value'])

In [227]:
life['indicator'] = life['indicator'].str.split('(', expand = True)[0]

In [228]:
life['indicator'] = life['indicator'].str.split(',', expand = True)[0]

In [229]:
life

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,Life expectancy at birth,Africa Eastern and Southern,AFE,2025,NaN,,,0
1,Life expectancy at birth,Africa Eastern and Southern,AFE,2024,65.349930,,,0
2,Life expectancy at birth,Africa Eastern and Southern,AFE,2023,65.146228,,,0
3,Life expectancy at birth,Africa Eastern and Southern,AFE,2022,64.487152,,,0
4,Life expectancy at birth,Africa Eastern and Southern,AFE,2021,62.979999,,,0
...,...,...,...,...,...,...,...,...
17485,Life expectancy at birth,Zimbabwe,ZWE,1964,55.431000,,,0
17486,Life expectancy at birth,Zimbabwe,ZWE,1963,54.942000,,,0
17487,Life expectancy at birth,Zimbabwe,ZWE,1962,54.453000,,,0
17488,Life expectancy at birth,Zimbabwe,ZWE,1961,53.966000,,,0
17489,Life expectancy at birth,Zimbabwe,ZWE,1960,53.492000,,,0

In [230]:
life = life.drop(columns = ['unit','obs_status','decimal','indicator']).copy()

In [231]:
life

                           country countryiso3code  date      value
0      Africa Eastern and Southern             AFE  2025        NaN
1      Africa Eastern and Southern             AFE  2024  65.349930
2      Africa Eastern and Southern             AFE  2023  65.146228
3      Africa Eastern and Southern             AFE  2022  64.487152
4      Africa Eastern and Southern             AFE  2021  62.979999
...                            ...             ...   ...        ...
17485                     Zimbabwe             ZWE  1964  55.431000
17486                     Zimbabwe             ZWE  1963  54.942000
17487                     Zimbabwe             ZWE  1962  54.453000
17488                     Zimbabwe             ZWE  1961  53.966000
17489                     Zimbabwe             ZWE  1960  53.492000

[17490 rows x 4 columns]

In [232]:
gdp = gdp.drop(columns = ['unit','obs_status','decimal','indicator']).copy()

In [233]:
gdp

                           country countryiso3code  date        value
0      Africa Eastern and Southern             AFE  2025          NaN
1      Africa Eastern and Southern             AFE  2024  4106.434140
2      Africa Eastern and Southern             AFE  2023  4083.993003
3      Africa Eastern and Southern             AFE  2022  4106.501907
4      Africa Eastern and Southern             AFE  2021  4056.113017
...                            ...             ...   ...          ...
17485                     Zimbabwe             ZWE  1964          NaN
17486                     Zimbabwe             ZWE  1963          NaN
17487                     Zimbabwe             ZWE  1962          NaN
17488                     Zimbabwe             ZWE  1961          NaN
17489                     Zimbabwe             ZWE  1960          NaN

[17490 rows x 4 columns]

In [234]:
gdp = gdp.rename(columns = {'value':'gdp'}).copy()

In [235]:
gdp

                           country countryiso3code  date          gdp
0      Africa Eastern and Southern             AFE  2025          NaN
1      Africa Eastern and Southern             AFE  2024  4106.434140
2      Africa Eastern and Southern             AFE  2023  4083.993003
3      Africa Eastern and Southern             AFE  2022  4106.501907
4      Africa Eastern and Southern             AFE  2021  4056.113017
...                            ...             ...   ...          ...
17485                     Zimbabwe             ZWE  1964          NaN
17486                     Zimbabwe             ZWE  1963          NaN
17487                     Zimbabwe             ZWE  1962          NaN
17488                     Zimbabwe             ZWE  1961          NaN
17489                     Zimbabwe             ZWE  1960          NaN

[17490 rows x 4 columns]

In [236]:
life = life.rename(columns = {'value':'life_expectancy'}).copy()

In [237]:
life

                           country countryiso3code  date  life_expectancy
0      Africa Eastern and Southern             AFE  2025              NaN
1      Africa Eastern and Southern             AFE  2024        65.349930
2      Africa Eastern and Southern             AFE  2023        65.146228
3      Africa Eastern and Southern             AFE  2022        64.487152
4      Africa Eastern and Southern             AFE  2021        62.979999
...                            ...             ...   ...              ...
17485                     Zimbabwe             ZWE  1964        55.431000
17486                     Zimbabwe             ZWE  1963        54.942000
17487                     Zimbabwe             ZWE  1962        54.453000
17488                     Zimbabwe             ZWE  1961        53.966000
17489                     Zimbabwe             ZWE  1960        53.492000

[17490 rows x 4 columns]

In [238]:
big = pd.merge(left = gdp, right = life, how = 'left')

In [239]:
big

,country,countryiso3code,date,gdp,life_expectancy
0,Africa Eastern and Southern,AFE,2025,NaN,NaN
1,Africa Eastern and Southern,AFE,2024,4106.434140,65.349930
2,Africa Eastern and Southern,AFE,2023,4083.993003,65.146228
3,Africa Eastern and Southern,AFE,2022,4106.501907,64.487152
4,Africa Eastern and Southern,AFE,2021,4056.113017,62.979999
...,...,...,...,...,...
17485,Zimbabwe,ZWE,1964,NaN,55.431000
17486,Zimbabwe,ZWE,1963,NaN,54.942000
17487,Zimbabwe,ZWE,1962,NaN,54.453000
17488,Zimbabwe,ZWE,1961,NaN,53.966000
17489,Zimbabwe,ZWE,1960,NaN,53.492000

In [240]:
endpoint = 'https://api.worldbank.org/v2/country'
params = {
    'format': 'json',
    'per_page': '295'
}
request = requests.get(endpoint, params = params)
request

In [241]:
country = request.json()

In [242]:
country[0]

{'page': 1, 'pages': 1, 'per_page': '295', 'total': 295}

In [243]:
country = pd.DataFrame(country[1])

In [244]:
country

,id,iso2Code,name,region,adminregion,incomeLevel,lendingType,capitalCity,longitude,latitude
0,ABW,AW,Aruba,"{'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Lati...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...","{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",Oranjestad,-70.0167,12.5167
1,AFE,ZH,Africa Eastern and Southern,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
2,AFG,AF,Afghanistan,"{'id': 'MEA', 'iso2code': 'ZQ', 'value': 'Midd...","{'id': 'MNA', 'iso2code': 'XQ', 'value': 'Midd...","{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Kabul,69.1761,34.5228
3,AFR,A9,Africa,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
4,AFW,ZI,Africa Western and Central,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
...,...,...,...,...,...,...,...,...,...,...
290,XZN,A5,Sub-Saharan Africa excluding South Africa and ...,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
291,YEM,YE,"Yemen, Rep.","{'id': 'MEA', 'iso2code': 'ZQ', 'value': 'Midd...","{'id': 'MNA', 'iso2code': 'XQ', 'value': 'Midd...","{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Sana'a,44.2075,15.352
292,ZAF,ZA,South Africa,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-...","{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'UMC', 'iso2code': 'XT', 'value': 'Uppe...","{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",Pretoria,28.1871,-25.746
293,ZMB,ZM,Zambia,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-...","{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'LMC', 'iso2code': 'XN', 'value': 'Lowe...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Lusaka,28.2937,-15.3982
294,ZWE,ZW,Zimbabwe,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-...","{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'LMC', 'iso2code': 'XN', 'value': 'Lowe...","{'id': 'IDB', 'iso2code': 'XH', 'value': 'Blend'}",Harare,31.0672,-17.8312

In [245]:
country['region'] = country['region'].apply(lambda x : x['value'])

In [246]:
country

,id,iso2Code,name,region,adminregion,incomeLevel,lendingType,capitalCity,longitude,latitude
0,ABW,AW,Aruba,Latin America & Caribbean,"{'id': '', 'iso2code': '', 'value': ''}","{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...","{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",Oranjestad,-70.0167,12.5167
1,AFE,ZH,Africa Eastern and Southern,Aggregates,"{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
2,AFG,AF,Afghanistan,"Middle East, North Africa, Afghanistan & Pakistan","{'id': 'MNA', 'iso2code': 'XQ', 'value': 'Midd...","{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Kabul,69.1761,34.5228
3,AFR,A9,Africa,Aggregates,"{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
4,AFW,ZI,Africa Western and Central,Aggregates,"{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
...,...,...,...,...,...,...,...,...,...,...
290,XZN,A5,Sub-Saharan Africa excluding South Africa and ...,Aggregates,"{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
291,YEM,YE,"Yemen, Rep.","Middle East, North Africa, Afghanistan & Pakistan","{'id': 'MNA', 'iso2code': 'XQ', 'value': 'Midd...","{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Sana'a,44.2075,15.352
292,ZAF,ZA,South Africa,Sub-Saharan Africa,"{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'UMC', 'iso2code': 'XT', 'value': 'Uppe...","{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",Pretoria,28.1871,-25.746
293,ZMB,ZM,Zambia,Sub-Saharan Africa,"{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'LMC', 'iso2code': 'XN', 'value': 'Lowe...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Lusaka,28.2937,-15.3982
294,ZWE,ZW,Zimbabwe,Sub-Saharan Africa,"{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'LMC', 'iso2code': 'XN', 'value': 'Lowe...","{'id': 'IDB', 'iso2code': 'XH', 'value': 'Blend'}",Harare,31.0672,-17.8312

In [247]:
country['incomeLevel'] = country['incomeLevel'].apply(lambda x : x['value'])
country['adminregion'] = country['adminregion'].apply(lambda x : x['value'])
country['lendingType'] = country['lendingType'].apply(lambda x : x['value'])

In [248]:
country

,id,iso2Code,name,region,adminregion,incomeLevel,lendingType,capitalCity,longitude,latitude
0,ABW,AW,Aruba,Latin America & Caribbean,,High income,Not classified,Oranjestad,-70.0167,12.5167
1,AFE,ZH,Africa Eastern and Southern,Aggregates,,Aggregates,Aggregates,,,
2,AFG,AF,Afghanistan,"Middle East, North Africa, Afghanistan & Pakistan","Middle East, North Africa, Afghanistan & Pakis...",Low income,IDA,Kabul,69.1761,34.5228
3,AFR,A9,Africa,Aggregates,,Aggregates,Aggregates,,,
4,AFW,ZI,Africa Western and Central,Aggregates,,Aggregates,Aggregates,,,
...,...,...,...,...,...,...,...,...,...,...
290,XZN,A5,Sub-Saharan Africa excluding South Africa and ...,Aggregates,,Aggregates,Aggregates,,,
291,YEM,YE,"Yemen, Rep.","Middle East, North Africa, Afghanistan & Pakistan","Middle East, North Africa, Afghanistan & Pakis...",Low income,IDA,Sana'a,44.2075,15.352
292,ZAF,ZA,South Africa,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Upper middle income,IBRD,Pretoria,28.1871,-25.746
293,ZMB,ZM,Zambia,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,IDA,Lusaka,28.2937,-15.3982
294,ZWE,ZW,Zimbabwe,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,Blend,Harare,31.0672,-17.8312

In [249]:
country.columns

Index(['id', 'iso2Code', 'name', 'region', 'adminregion', 'incomeLevel',
       'lendingType', 'capitalCity', 'longitude', 'latitude'],
      dtype='object')

In [250]:
country = country.drop(columns = ['iso2Code','adminregion']).copy()

In [251]:
big

,country,countryiso3code,date,gdp,life_expectancy
0,Africa Eastern and Southern,AFE,2025,NaN,NaN
1,Africa Eastern and Southern,AFE,2024,4106.434140,65.349930
2,Africa Eastern and Southern,AFE,2023,4083.993003,65.146228
3,Africa Eastern and Southern,AFE,2022,4106.501907,64.487152
4,Africa Eastern and Southern,AFE,2021,4056.113017,62.979999
...,...,...,...,...,...
17485,Zimbabwe,ZWE,1964,NaN,55.431000
17486,Zimbabwe,ZWE,1963,NaN,54.942000
17487,Zimbabwe,ZWE,1962,NaN,54.453000
17488,Zimbabwe,ZWE,1961,NaN,53.966000
17489,Zimbabwe,ZWE,1960,NaN,53.492000

In [252]:
big = big.rename(columns = {'countryiso3code':'id'}).copy()

In [253]:
big = big.merge(country, on = 'id', how = 'left').copy()

In [254]:
big.head()

,country,id,date,gdp,life_expectancy,name,region,incomeLevel,lendingType,capitalCity,longitude,latitude
0,Africa Eastern and Southern,AFE,2025,NaN,NaN,Africa Eastern and Southern,Aggregates,Aggregates,Aggregates,,,
1,Africa Eastern and Southern,AFE,2024,4106.434140,65.349930,Africa Eastern and Southern,Aggregates,Aggregates,Aggregates,,,
2,Africa Eastern and Southern,AFE,2023,4083.993003,65.146228,Africa Eastern and Southern,Aggregates,Aggregates,Aggregates,,,
3,Africa Eastern and Southern,AFE,2022,4106.501907,64.487152,Africa Eastern and Southern,Aggregates,Aggregates,Aggregates,,,
4,Africa Eastern and Southern,AFE,2021,4056.113017,62.979999,Africa Eastern and Southern,Aggregates,Aggregates,Aggregates,,,

In [256]:
big = big.drop(columns = ['region'])

In [257]:
big

,country,id,date,gdp,life_expectancy,name,incomeLevel,lendingType,capitalCity,longitude,latitude
0,Africa Eastern and Southern,AFE,2025,NaN,NaN,Africa Eastern and Southern,Aggregates,Aggregates,,,
1,Africa Eastern and Southern,AFE,2024,4106.434140,65.349930,Africa Eastern and Southern,Aggregates,Aggregates,,,
2,Africa Eastern and Southern,AFE,2023,4083.993003,65.146228,Africa Eastern and Southern,Aggregates,Aggregates,,,
3,Africa Eastern and Southern,AFE,2022,4106.501907,64.487152,Africa Eastern and Southern,Aggregates,Aggregates,,,
4,Africa Eastern and Southern,AFE,2021,4056.113017,62.979999,Africa Eastern and Southern,Aggregates,Aggregates,,,
...,...,...,...,...,...,...,...,...,...,...,...
17485,Zimbabwe,ZWE,1964,NaN,55.431000,Zimbabwe,Lower middle income,Blend,Harare,31.0672,-17.8312
17486,Zimbabwe,ZWE,1963,NaN,54.942000,Zimbabwe,Lower middle income,Blend,Harare,31.0672,-17.8312
17487,Zimbabwe,ZWE,1962,NaN,54.453000,Zimbabwe,Lower middle income,Blend,Harare,31.0672,-17.8312
17488,Zimbabwe,ZWE,1961,NaN,53.966000,Zimbabwe,Lower middle income,Blend,Harare,31.0672,-17.8312
17489,Zimbabwe,ZWE,1960,NaN,53.492000,Zimbabwe,Lower middle income,Blend,Harare,31.0672,-17.8312